<div class="main-panel">
    <!-- Navbar -->
    <nav id="navegacao" class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container-fluid">
            <div class="navbar-wrapper">
                <div class="navbar-toggle">
                    <button type="button" class="navbar-toggler">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
    <!-- Fim navbar -->

    <div class="content">
        <div class="row">
            <div class="col-md-12 ml-auto mr-auto">
                <div class="navbar-wrapper text-center">
                    <a class="navbar-brand">Faça cópia dos dados em planilha excel</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mr-auto ml-auto">
                <div class="form-group" style="margin-top: 20px">
                    <select id="backupMenu" class="form-control">
                        <option selected disabled>Escolha a tabela que deseja baixar</option>
                        <option value="1">Vítimas</option>
                        <option value="2">Recordações</option>
                        <option value="3">Informações</option>
                        <option value="4">Documentos</option>
                    </select>
                </div>
            </div>
            <br /><br /><br />
        </div>
        <div class="row">
            <div class="col-md-12 ml-auto mr-auto" style="text-align: center;">
                <button id="backupBtn" class="btn btn-outline-default btn-round" style="display: none">
                    <i class="fas fa-save fa-lg"></i>&nbsp;&nbsp;Baixar
                </button>
            </div>
        </div>
    </div>
</div>