
<link href="../public/assets/dashboard/css/formatacao-comentarios.css" rel="stylesheet" />

<div class="main-panel">
    <!-- Navbar -->
    <nav id="navegacao" class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <div class="navbar-toggle">
                    <button type="button" class="navbar-toggler">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
    <!-- Fim navbar -->    

    <!-- Modal comentario -->
    <div class="modal fade" id="modalMensagem" tabindex="-1" role="dialog" aria-labelledby="modalMensagem" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5 id="textoModal"></h5>
                </div>
                <div class="modal-footer">
                    <div class="right-side">
                        <button type="button" class="btn btn-danger btn-link" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim modal comentario-->

    <div class="content">
        <div class="row">
            <div class="col-md-12 ml-auto mr-auto">
                <div class="navbar-wrapper">
                    <a class="navbar-brand">Recordações recebidas</a>
                </div>
            </div>
        </div>

        <?php foreach ($this->view->comentarios as $key => $comentario) { ?>
            <div class="row secaoComentario">
                <div class="col-md-10 ml-auto mr-auto">
                    <div class="card card-user">
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Id da vítima</label>
                                            <div id="idVitima" class="form-control"><?php echo $comentario['fk_idVitima'] ?></div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label>Nome da Vítima</label>
                                            <div id="idade" class="form-control"><?php echo $comentario['nome'] ?></div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Página da Vítima</label>
                                            <div id="pagina" class="form-control"><a target="_blank" href="/vitima?id=<?php echo $comentario['fk_idVitima'] ?>">Acessar</a></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Remetente</label>
                                            <div id="nome" class="form-control"><?php echo $comentario['autor'] ?></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>E-mail do Remetente</label>
                                            <div id="email" class="form-control"><?php echo $comentario['email'] ?></div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Recordação realizada:</label>
                                            <textarea id="comentario" class="form-control" rows="3" placeholder="Descrição" style="cursor: auto" disabled><?php echo $comentario['comentario'] ?></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <footer>
                                            <div class="container dataHora">
                                                <div class="copyright float-left">
                                                    Recordação feita em: <br /><?php echo date('d/m/Y H:i', strtotime($comentario['data'])); ?>
                                                </div>
                                            </div>
                                        </footer>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="ml-auto float-right">
                                            <button type="button" data-id_rejeitar="<?php echo $comentario['idComentario']; ?>" class="btn btn-danger btn-round btnRejeitar">REJEITAR</button>
                                            <button type="button" data-id_aceitar="<?php echo $comentario['idComentario']; ?>" class="btn btn-primary btn-round btnAceitar">ACEITAR</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- end col-md-12 -->
            </div>
        <?php } ?>
        <!-- end row -->
    </div>

    <!-- rodape -->
    <footer class="footer footer-default">
        <div class="container">
            <div class="copyright float-right">
                Desenvolvedor: Rafael Nascimento<br />rdsnascimento@inf.ufpel.edu.br
            </div>
        </div>
    </footer>
    <!-- fim rodape -->
</div>