<link href="../public/assets/dashboard/css/formatacao-comentarios.css" rel="stylesheet" />

<style>
    .nav-tabs-navigation {
        text-align: center;
        border-bottom: 1px solid #F1EAE0;
        margin-bottom: 30px;
    }

    .nav-tabs-wrapper {
        display: inline-block;

        position: relative;
        width: auto;
    }

    .nav-tabs .nav-item.show .nav-link,
    .nav-tabs .nav-link.active {
        color: #495057;
        background-color: inherit;
        border-color: #dee2e6 #dee2e6 #f4f3ef;
    }

    .nav-tabs-navigation {
        text-align: center;
        border-bottom: 1px solid #dee2e6;
        margin-top: 15px;
    }

    .nav-tabs {
        border-bottom: 0 none;
    }

    .nav {
        display: flex;
        flex-wrap: wrap;
        padding-left: 0;
        margin-bottom: 0;
        list-style: none;
    }

    .nav-item>a {
        color: #9b9b9b;
    }
</style>

<div class="main-panel">
    <!-- Navbar -->
    <nav id="navegacao" class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <div class="navbar-toggle">
                    <button type="button" class="navbar-toggler">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
    <!-- Fim navbar -->

    <!-- Modal comentario -->
    <div class="modal fade" id="modalMensagem" tabindex="-1" role="dialog" aria-labelledby="modalMensagem" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" style="border: none">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="border: none; padding-top: 0; padding-bottom: 0;">
                    <h5 id="textoModal"></h5>
                </div>
                <div class="modal-footer" style="border: none; padding-top: 0;">
                    <div class="right-side">
                        <button type="button" class="btn btn-danger btn-link" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim modal comentario-->

    <!-- Modal sem reload de pagina -->
    <div class="modal fade" id="modalMensagemSemReload" tabindex="-1" role="dialog" aria-labelledby="modalMensagem" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" style="border: none">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="border: none; padding-top: 0; padding-bottom: 0;">
                    <h5 id="textoModalSemReload"></h5>
                </div>
                <div class="modal-footer" style="border: none; padding-top: 0;">
                    <div class="right-side">
                        <button type="button" class="btn btn-danger btn-link" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim modal comentario-->

    <div class="content">
        <div class="row">
            <div class="col-md-12 ml-auto mr-auto">
                <div class="navbar-wrapper">
                    <a class="navbar-brand">Recordações</a>
                </div>
            </div>
        </div>

        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#tabrecebidas" role="tab">Recebidas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#tabadicionar" role="tab">Adicionar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#tabremover" role="tab">Visualizar/Remover</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="tab-content">
            <div class="tab-pane active" id="tabrecebidas" role="tabpanel">
                <?php if ($this->view->comentarios == NULL) { ?>
                
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div style="font-size: 14px; margin-top:10px">O Memorial não recebeu nenhuma recordação nova</div>
                    </div>
                </div>
                
                <?php } else {
                foreach ($this->view->comentarios as $key => $comentario) { ?>
                        <div class="row secaoComentario">
                            <div class="col-md-10 ml-auto mr-auto">
                                <div class="card card-user">
                                    <div class="card-body">
                                        <form>
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <div class="form-group">
                                                        <label>Id da vítima</label>
                                                        <div id="idVitima" class="form-control"><?php echo $comentario['fk_idVitima'] ?></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="form-group">
                                                        <label>Nome da Vítima</label>
                                                        <div class="form-control"><?php echo $comentario['nome'] ?></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2">
                                                    <div class="form-group">
                                                        <label>Página da Vítima</label>
                                                        <div id="pagina" class="form-control"><a target="_blank" href="/vitima?id=<?php echo $comentario['fk_idVitima'] ?>">Acessar</a></div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>Remetente</label>
                                                        <div id="nome" class="form-control"><?php echo $comentario['autor'] ?></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>E-mail do Remetente</label>
                                                        <div id="email" class="form-control"><?php echo $comentario['email'] ?></div>
                                                    </div>
                                                </div>

                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>Recordação realizada:</label>
                                                        <textarea id="comentario" class="form-control" rows="3" placeholder="Descrição" style="cursor: auto" disabled><?php echo $comentario['comentario'] ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <footer>
                                                        <div class="container dataHora">
                                                            <div class="copyright float-left">
                                                                Recordação feita em: <br /><?php echo date('d/m/Y H:i', strtotime($comentario['data'])); ?>
                                                            </div>
                                                        </div>
                                                    </footer>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="ml-auto float-right">
                                                        <button type="button" data-id_rejeitar="<?php echo $comentario['idComentario']; ?>" class="btn btn-danger btn-round btnRejeitar">REJEITAR</button>
                                                        <button type="button" data-id_aceitar="<?php echo $comentario['idComentario']; ?>" class="btn btn-primary btn-round btnAceitar">ACEITAR</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- end col-md-12 -->
                        </div>
                    <?php
                }
            }
            ?>
                <!-- end row -->
            </div>

            <div class="tab-pane" id="tabremover" role="tabpanel">
                <div class="row">
                    <div class="col-md-6 mr-auto ml-auto">
                        <div class="form-group">
                            <select id="listarComentariosAceitos" class="form-control">
                                <option selected disabled>Selecione a vítima para visualizar/remover</option>
                                <?php foreach ($this->view->vitimas as $key => $vitima) { ?>
                                    <option value="<?php echo $vitima['idVitima']; ?>"><?php echo $vitima['nome']; ?></option>
                                <?php
                            } ?>
                            </select>
                        </div>
                    </div>
                    <br /><br /><br />
                </div>

                <div id="recordacoesRecebidas" style="display:none">
                    <div class="row">
                        <div id="campoDeRecordacoes" class="col-md-10 ml-auto mr-auto">
                        </div> <!-- recebe as recordacoes dinamicamente do bd -->
                    </div>
                </div>
            </div>

            <div class="tab-pane" id="tabadicionar" role="tabpanel">
                <div class="row">
                    <div class="col-md-6 mr-auto ml-auto">
                        <div class="form-group">
                            <select id="vtmAdicionarRecordacao" class="form-control">
                                <option selected disabled>Selecione a vítima para adicionar</option>
                                <?php foreach ($this->view->vitimas as $key => $vitima) { ?>
                                    <option value="<?php echo $vitima['idVitima']; ?>"><?php echo $vitima['nome']; ?></option>
                                <?php
                            } ?>
                            </select>
                        </div>
                    </div>
                    <br /><br /><br />
                </div>

                <div id="recordacoesAdicionar" class="row" style="display:none">
                    <div class="col-md-9 mr-auto ml-auto">
                        <div class="card card-user">
                            <div class="card-header">
                                <div class="text-center">
                                    <h5 class="card-title">
                                        Adicionar recordação&nbsp&nbsp
                                        <a id="linkVtm" target="_blank" title="Acessar perfil da vítima">
                                            <i class="fas fa-external-link-alt" style="font-size: 18px"></i>
                                        </a>
                                    </h5>
                                    <sup>Exclusivo para adicionar recordações da vítima que foram publicadas em algum lugar (como jornal).</sup>
                                    <br /><br />
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 col-6">
                                        <div class="form-group">
                                            <label>Nome (autor)</label>
                                            <input id="recordacaoNome" name="nome" type="text" class="form-control" placeholder="Nome" autocomplete="off" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-6">
                                        <div class="form-group">
                                            <label>Sobrenome (autor)</label>
                                            <input id="recordacaoSobrenome" name="sobrenome" type="text" class="form-control" placeholder="Sobrenome" autocomplete="off" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nome do Periódico</label>
                                            <input id="recordacaoPeriodico" name="legenda" type="text" class="form-control" placeholder="Exemplo: Diário de Santa Maria" autocomplete="off" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-6">
                                        <div class="form-group">
                                            <label>Data</label>
                                            <input id="recordacaoData" type="date" class="form-control" required>
                                        </div>
                                    </div>
                                    <div class="col-md-2 col-6">
                                        <div class="form-group">
                                            <label>Página</label>
                                            <input id="recordacaoPagina" class="form-control" type="number" min="1" placeholder="Número" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Recordação</label>
                                            <textarea id="recordacaoDescricao" name="descricao" class="form-control ckeditor" rows="10" placeholder="Digite a recordação" required></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="ml-auto mr-auto">
                                        <button id="btnAdicionarRecordacao" type="button" class="btn btn-primary btn-round">Adicionar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- rodape -->
    <footer class="footer footer-default">
        <div class="container">
            <div class="copyright float-right">
                Desenvolvedor: Rafael Nascimento<br />rdsnascimento@inf.ufpel.edu.br
            </div>
        </div>
    </footer>
    <!-- fim rodape -->
</div>