<div class="main-panel">
    <!-- Navbar -->
    <nav id="navegacao" class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <div class="navbar-toggle">
                    <button type="button" class="navbar-toggler">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
    <!-- Fim navbar -->

    <!-- Conteudo -->
    <div class="content">
        <div class="row">
            <div class="col-md-6 mr-auto ml-auto">
                <div class="form-group">
                    <select id="vitimas" name="vitimas" class="form-control">
                        <option selected disabled>Selecione a vítima</option>
                        <?php foreach ($this->view->vitimas as $key => $vitima) { ?>
                            <option value="<?php echo $vitima['idVitima']; ?>"><?php echo $vitima['nome']; ?></option>
                        <?php
                    } ?>
                    </select>
                </div>
            </div>
            <br /><br /><br />
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card card-user">
                    <div class="image">
                        <img id="foto_capa" src="../public/assets/dashboard/img/fotografias/frente2.jpg" alt="...">
                    </div>
                    <div class="card-body">
                        <div class="author">
                            <img class="avatar border-gray" src="../public/img/vitimas/<?php echo $this->view->vtm['foto_perfil'] ?>" id="foto_perfil">
                            <div class="alterar-imagem">
                                <a id="pagina-vitima" target="_blank" href="/vitima?id=<?php echo $this->view->vtm['idVitima'] ?>" class="btn btn-info btn-icon"><i class="fas fa-user-alt"></i></a>
                            </div>
                            <h5 id="card-nome" class="title"><?php echo $this->view->vtm['nome'] ?></h5>
                            <p id="card-cidade"><?php if ($this->view->vtm['cidade'] != '') {
                                                    echo $this->view->vtm['cidade'];
                                                } else {
                                                    echo "Cidade";
                                                } ?></p>
                        </div>
                        <p id="card-legenda" class="card-legenda text-center">
                            <?php if ($this->view->vtm['legenda'] != '') {
                                echo $this->view->vtm['legenda'];
                            } else {
                                echo "Legenda";
                            } ?>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card card-user">
                    <div class="card-header">
                        <h5 class="card-title">Editar Perfil 
                            <span id="desativado" style="font-size: 15px; color: #EF855D; 
                                <?php if($this->view->vtm['estado'] == '0'){?>
                                    display: inline
                                <?php } else { ?>
                                    display: none
                                <?php } ?>">(desativado)
                            </span></h5>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input id="nome" name="nome" type="text" class="form-control" placeholder="Nome" required value="<?php echo $this->view->vtm['nome'] ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Id</label>
                                        <input id="idVitima" disabled class="form-control" placeholder="Id" value="<?php echo $this->view->vtm['idVitima'] ?>">
                                        <input id="idVtm" name="id" type="hidden" required>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Sexo</label>
                                        <input id="sexo" disabled name="sexo" type="text" class="form-control" value="<?php if($this->view->vtm['sexo'] == '0') { echo "M";} else { echo "F"; }?>">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Idade</label>
                                        <input id="idade" name="idade" type="number" class="form-control" placeholder="Idade" value="<?php echo $this->view->vtm['idade'] ?>">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Cidade</label>
                                        <input id="cidade" name="cidade" type="text" class="form-control" placeholder="Cidade" value="<?php echo $this->view->vtm['cidade'] ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Legenda</label>
                                        <input id="legenda" name="legenda" type="text" class="form-control" placeholder="Legenda" value="<?php echo $this->view->vtm['legenda'] ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>
                                        <textarea id="descricao" name="descricao" class="form-control ckeditor" rows="14" placeholder="Descrição" required><?php echo $this->view->vtm['descricao'] ?></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>Vítima</label>
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input id="status" class="form-check-input" type="checkbox" <?php if($this->view->vtm['estado'] == '0') echo 'checked'; ?>>
                                                Desativar
                                                <span class="form-check-sign">
                                                    <span class="check"></span>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="ml-auto mr-auto">
                                    <button id="btnAtualizarVitima" type="button" class="btn btn-primary btn-round">Atualizar perfil</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fim do conteúdo -->

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5>Cadastro atualizado com sucesso!</h5>
                </div>
                <div class="modal-footer">
                    <div class="right-side">
                        <button type="button" class="btn btn-danger btn-link" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim modal -->

    <!-- rodape -->
    <footer class="footer footer-default">
        <div class="container">
            <div class="copyright float-right">
                Desenvolvedor: Rafael Nascimento<br />rdsnascimento@inf.ufpel.edu.br
            </div>
        </div>
    </footer>
    <!-- fim rodape -->
</div>