<style>
    .tituloVidas {
        font-size: 70px; 
        /* letter-spacing: 9px */
    }

    .secaoTextoMosaico{
        text-align: justify;
    }

    @media only screen and (max-width: 499px){
        .tituloVidas {
            /* letter-spacing: 2px; */
            font-size: 29px;
        }

        .secaoTextoMosaico{
            padding: 8px 12px;
        }
    }

    @media only screen and (min-width: 500px) and (max-width: 1080px) {
        .tituloVidas {
            /* letter-spacing: 3px; */
            font-size: 40px;
        }

        .secaoTextoMosaico{
            padding: 10px 15px;
        }
    }
</style>

<!-- Navegacao -->
<nav class="navbar navbar-transparent fixed-top navbar-expand-lg" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/">Início</a>
        </div>
    </div>
</nav>
<!-- Fim navegacao -->

<div class="page-header header-filter header-small" data-parallax="true" style="background-image: url('public/img/fotografias/ciluetas.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-12 ml-auto mr-auto text-center">
                <div class="title">
                    <div class="tituloVidas">27 de janeiro de 2013</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main main-raised" style="background: linear-gradient(0deg, #E5E5E5 0%, #fff 100%);">
    <div>
        <div class="container">
            <div class="row">
                <div class="container">
                    <div class="section section-text secaoTextoMosaico">
                        <div class="row">
                            <div class="col-md-10 ml-auto mr-auto">
                                <!-- <h3 class="title">Moisaco das Vidas</h3> -->
                                <h4>
                                    Na madrugada de 27 de janeiro de 2013 um incêndio provocado pelas faíscas de um sinalizador externo usado no interior da boate, 
                                    em contato com o teto altamente inflamável e tóxico, provocou a morte de 235 pessoas e deixou mais de 650 feridos. 
                                    os dias que se seguiram ao incêndio, outras 7 pessoas vieram a falecer.  
                                    Na boate estima-se que haviam mais de mil pessoa no dia da tragédia. 
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <nav class="float-left">
            <ul>
                <li><a href="/">Inicio</a></li>
                <li><a href="/portal">Portal</a></li>
            </ul>
        </nav>
        <div class="copyright float-right" style="font-size: 14px;">
            © <span id="anoRodape"></span> Memorial Virtual Kiss<br />
            <div style="font-size: 12px; margin-top: -5px;">Desenvolvedor: Rafael Nascimento<br />
                <div style="font-size: 12px; margin-top: -5px">rdsnascimento@inf.ufpel.edu.br</div>
            </div>
        </div>
    </div>
</footer>