<style>
    .tituloVidas {
        font-size: 95px; 
        letter-spacing: 5px
    }

    .secaoTextoMosaico{
        text-align: justify;
    }

    @media only screen and (max-width: 600px) {
        .tituloVidas {
            letter-spacing: 3px;
            font-size: 62px;
        }

        .secaoTextoMosaico{
            padding: 10px 15px;
        }
    }
</style>

<!-- Navegacao -->
<nav class="navbar navbar-transparent fixed-top navbar-expand-lg" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/">Início</a>
            <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button> -->
        </div>
    </div>
</nav>
<!-- Fim navegacao -->

<div class="page-header header-filter header-small" data-parallax="true" style="background-image: url('public/img/mural.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto text-center">
                <div class="title tituloVidas">242 VIDAS</div>
                <!-- <h4>Aqui tecemos um pouco da história de vida daqueles que<br/>antecipadamente foram tirados de nossa convivência</h4> -->
            </div>
        </div>
    </div>
</div>

<div class="main main-raised" style="background: linear-gradient(0deg, #E5E5E5 0%, #fff 100%);">
    <div>
        <div class="container">
            <div class="row">
                <div class="container">
                    <div class="section section-text secaoTextoMosaico">
                        <div class="row">
                            <div class="col-md-10 ml-auto mr-auto">
                                <h3 class="title">Moisaco das Vidas</h3>
                                <h4>
                                    242 é o número de homens e mulheres, meninos e meninas que podes conhecer em tua
                                    visita. Estes foram vitimados pelo incêndio na boate Kiss, em 27 de janeiro de 2013. O
                                    mosaico abaixo apresentado é um espaço de homenagem e visa a construção coletiva da
                                    biografia de cada um deles.
                                    <br/><br/>
                                    Quem eram, de onde vieram, o que faziam em Santa Maria. Que lembranças seus familiares a amigos guardam com carinho?
                                    <br/><br/>
                                    Dentro do perfil, possibilita-se que sejam acrescidas recordações por meio de novos depoimentos, textos, imagens e/ou vídeos sobre essas pessoas. Contribua com este processo.
                                </h4>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-10 ml-auto mr-auto">
                                <h4 class="text-center text-muted" style="padding-bottom: 35px"></h4>
                                <div class="demo-gallery">
                                    <div class="galeriaJovens">
                                        <?php foreach ($this->view->vidas as $key => $vida) { ?>
                                            <a href='/vitima?id=<?= $vida['idVitima'] ?>'>
                                                <img alt='<?= $vida['nome'] ?>' src='public/img/vitimas/<?= $vida['foto_perfil'] ?>' />
                                            </a>
                                        <?php
                                        } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <nav class="float-left">
            <ul>
                <li><a href="/">Inicio</a></li>
                <li><a href="/portal">Portal</a></li>
            </ul>
        </nav>
        <div class="copyright float-right" style="font-size: 14px;">
            © <span id="anoRodape"></span> Memorial Virtual Kiss<br />
            <div style="font-size: 12px; margin-top: -5px;">Desenvolvedor: Rafael Nascimento<br />
                <div style="font-size: 12px; margin-top: -5px">rdsnascimento@inf.ufpel.edu.br</div>
            </div>
        </div>
    </div>
</footer>