<nav class="navbar navbar-transparent fixed-top navbar-expand-lg" onscroll="disableNavbar()" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/jovens">
                Ver todos
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <?php if ($this->view->perfil_vitima['idVitima'] > 1) { ?>
                        <a class="nav-link" href="/vitima?id=<?php echo ($this->view->perfil_vitima['idVitima'] - 1) ?>">
                            <i class="material-icons icone">arrow_back_ios</i> Anterior
                        </a>
                    <?php
                } ?>
                </li>
                <li class="nav-item">
                    <?php if ($this->view->perfil_vitima['idVitima'] < 242) { ?>
                        <a class="nav-link" href="/vitima?id=<?php echo ($this->view->perfil_vitima['idVitima'] + 1) ?>">
                            Próximo&nbsp&nbsp&nbsp<i class="material-icons icone">arrow_forward_ios</i>
                        </a>
                    <?php
                } ?>
                </li>
            </ul>
        </div>
    </div>
</nav>