<style>
    @media only screen and (max-width: 1080px){
        .follow {
            margin-top: 40px        
        }
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
                <div class="avatar">
                    <img src="public/img/vitimas/<?php
                                                    if ($this->view->perfil_vitima['estado'] == 1)
                                                        echo $this->view->perfil_vitima['foto_perfil'];
                                                    else
                                                        echo "00.jpg";
                                                    ?>" class="img-raised rounded-circle img-fluid">
                </div>
                <div class="name">
                    <h3 class="title"><?php echo $this->view->perfil_vitima['nome']; ?></h3>
                    <?php if ($this->view->perfil_vitima['estado'] == 1) { ?>
                        <span style="font-weight: 400; font-size: 17px">
                            <?php
                            if (($this->view->perfil_vitima['legenda']) != null) {
                                echo $this->view->perfil_vitima['legenda'];
                            } else {
                                if (($this->view->perfil_vitima['cidade']) != null) {
                                    echo $this->view->perfil_vitima['cidade'] . ". ";
                                }
                                if (($this->view->perfil_vitima['idade']) != null) {
                                    echo $this->view->perfil_vitima['idade'] . " anos";
                                }
                            }
                            ?>
                        </span>
                    <?php } ?>
                </div>
                <!-- Botao compartilhar -->
                <div class="follow">
                    <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fmemorialkiss.org%2Fvitima%3Fid%3D<?php echo $this->view->perfil_vitima['idVitima']; ?>&layout=button&size=small&width=97&height=20&appId" width="97" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                </div>
            </div>
        </div>
    </div>

    <!-- Se a vitima esta com status ativado no sistema -->
    <?php if ($this->view->perfil_vitima['estado'] == 1) { ?>
        <div class="col-md-12 ml-auto mr-auto">
            <div class="row">
                <div class="col-md-7 mr-auto ml-auto">
                    <!-- descricao -->
                    <div class="description text-center">
                        <div id="textoDescricao"><?php echo $this->view->perfil_vitima['descricao']; ?><br /></div>
                    </div>
                    <!-- fim descricao -->
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7 mr-auto ml-auto">
                <h4 class="text-center card-title" style="font-size: 22px; margin-top: 30px">Galeria de Memórias</h4><br />
                <div class="d-flex justify-content-center">
                    <div id="loaderGaleria" class="loader" style="display: none"></div>
                </div>
                <div class="demo-gallery">
                    <div id="galeria_fotos" idvitima="<?php echo $this->view->perfil_vitima['idVitima']; ?>"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7 col-sm-8 col-10 ml-auto mr-auto">
                <div id="painelRecordacoes" class="media-area" quantidade="<?php echo $this->view->contRecordacoes; ?>">
                    <h3 class="title text-center">Recordações</h3>

                    <?php if ($this->view->contRecordacoes == 0) { ?>
                        <div class="media-area">
                            <h4 class="text-center"><?php echo strstr($this->view->perfil_vitima['nome'], ' ', true); ?> ainda não tem nenhuma recordação.</h4>
                        </div>
                    <?php } ?>

                    <table class="table table-striped" style="margin-top: -15px">
                        <thead>
                            <tr id="colunasRecordacoes">
                                <th class="colunaTabela"></th>
                                <th class="colunaTabelaSimbolo"></th>
                                <th class="colunaTabela"></th>
                                <th class="colunaTabelaSimbolo"></th>
                                <th class="colunaTabela"></th>
                                <th class="colunaTabelaSimbolo"></th>
                            </tr>
                        </thead>
                        <tbody id="recordacoes"></tbody>
                    </table>
                    <nav>
                        <ul id="paginasRecordacoes" class="pagination justify-content-end"></ul>
                    </nav>
                </div>
            </div>
        </div>
    <?php } ?>
    <!-- fim de se vitima estiver com status de ativado -->
</div>
<!-- fim do carousel -->