<style>
    .main-raised {
        margin: 0px;
        border-radius: 0;
        box-shadow: none;
    }
</style>

<div class="main main-raised" id="principal">
    <div id="avtsm" class="section cd-section" style="padding-bottom: 150px">
        <div class="container">
            <div class="row">
                <div class="col-md-10 ml-auto mr-auto">
                    <h2 class="title text-center">AVTSM</h2>
                    <div class="row">
                        <div class="col-md-6">
                            <div>
                                <img class="logo-avtsm" src="public/img/logo-avtsm.png">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <h5 class="formatacaoTextoMobile">
                                A AVTSM (Associação dos Familiares de Vítimas e Sobreviventes da Tragédia de Santa
                                Maria) foi criada oficialmente no dia 23 de fevereiro de 2013 poucos dias depois da
                                tragedia.<br><br>A sua missão é assegurar os direitos e interesses bem como
                                garantir o auxílio e o amparo aos familiares das vítimas e aos sobreviventes da
                                tragédia.<br><br>A AVTSM luta pela defesa dos direitos e interesses dos
                                que sofreram com a morte de seus entes queridos, bem como daqueles que sobreviveram
                                ao ocorrido. Junto à luta pela justiça, a AVTSM promove a criação de um Memorial em
                                homenagem às vitímas. São seus representantes Sergio da Silva e Flávio Silva.
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    

    <!-- Equipe responsável -->
    <div class="section" id="headers" style="padding-top: 0px">
        <div id="equipe" class="team-4 section-image cd-section" style="background-image: url('public/img/capa2.jpg')">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto text-center">
                        <h2 class="title">Equipe responsável</h2><br /><br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-10 ml-auto mr-auto">
                        <div class="card card-profile card-efeito">
                            <div class="card-header card-avatar">
                                <a href="#">
                                    <img class="img" src="public/img/equipe/juliane.png" />
                                </a>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title titulo-card">Juliane Serres</h4>
                                <h6 class="card-category text-muted"></h6>
                                <p class="card-description fonte-card texto-card-equipe">
                                    Doutora em História pela UNISINOS<br />Professora PPG em Memória Social<br />e
                                    Patrimonio Cultural UFPEL
                                </p>
                                <br />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-10 ml-auto mr-auto card-distancia">
                        <div class="card card-profile card-efeito">
                            <div class="card-header card-avatar">
                                <a href="#">
                                    <img class="img" src="public/img/equipe/virginia.png" />
                                </a>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title titulo-card">Virginia Vecchioli</h4>
                                <p class="card-description fonte-card texto-card-equipe">
                                    Doutora em Antropologia pelo<br /> Museu Nacional UFRJ<br />Professora PPG em
                                    Ciências Sociais UFSM
                                </p>
                                <br />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-10 ml-auto mr-auto card-distancia">
                        <div class="card card-profile card-efeito">
                            <div class="card-header card-avatar">
                                <a href="#">
                                    <img class="img" src="public/img/equipe/leticia.png" />
                                </a>
                            </div>
                            <div class="card-body ">
                                <h4 class="card-title titulo-card">María Leticia Mazzucchi</h4>
                                <p class="card-description fonte-card texto-card-equipe">
                                    Doutora em História pela PUCRS<br />Professora PPG em Memória Social<br /> e
                                    Patrimonio Cultural UFPEL
                                </p>
                                <br />
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 col-10 ml-auto mr-auto">
                        <h2 class="title text-center" style="margin-top: 80px; margin-bottom: 30px">Comitê Científico</h2>
                        <div class="card">
                            <div class="card-body">
                                <h4>
                                    <ul class="card-title texto-comite">
                                        <li>Felipe Zene Motta, Arquiteto (Brasil)</li>
                                        <li>Joel Candau, Antropologo (França)</li>
                                        <li>Luis Carlos Toro Tamayo, Estudos Culturais (Colombia)</li>
                                        <li>Marcelo Canellas, Jornalista (Brasil)</li>
                                        <li>Marcio Seligmann-Silva, Teoria Literaria (Brasil)</li>
                                        <li>Núcleo de Estudios sobre Memoria (Argentina)</li>
                                        <li>Ruben Chababo, Letras (Argentina)</li>
                                        <li>Bolsista: Danilo Rangel, graduando em Museologia, UFPEL.</li>
                                        <li>Bolsista: Rafael Nascimento, graduando em Computação, UFPEL.</li>
                                        <li>Bolsista: Pedro Leal Gomes, estudante de Licenciatura em História, UFSM.</li>
                                        <li>Bolsista: Lucas Back de Araujo, graduando em Ciências Sociais, UFSM.</li>
                                    </ul>
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- fim equipe -->

    <!-- inicio do carrossel -->
    <div id="galeria" class="section cd-section section-white-gradient" style="padding-bottom: 150px">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mr-auto ml-auto">
                    <h2 class="title text-center">Galeria de Imagens</h2>

                    <h4 class="text-center text-muted texto-comite">Fotografias das Movimentações em Santa Maria.<br />Fotográfo: Dartanhan Baldez Figueiredo</h4><br />

                    <div class="demo-gallery">
                        <div id="galeria_fotos">
                            <a class="" href="public/img/fotografias/frente.jpg" data-sub-html="Frente da boate hoje">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/frente.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/ciluetas.jpg" data-sub-html="Silhuetas das vítimas">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/ciluetas.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/cartases.jpg" data-sub-html="Manifestação nas ruas de Santa Maria">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/cartases.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/vigilia.jpg" data-sub-html="Aniversário da tragédia">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/vigilia.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/desfile.jpg" data-sub-html="Manifestação nas ruas de Santa Maria">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/desfile.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/tenda.jpg" data-sub-html="Tenda da tragédia">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/tenda.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/marcha.jpg" data-sub-html="Passeata em Demanda de Justiça">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/marcha.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/movimiento.jpg" data-sub-html="Associação dos Familiares das Vítimas">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/movimiento.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/baile.jpg" data-sub-html="Tenda da Vigília">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/baile.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                            <a class="" href="public/img/fotografias/chicos.jpg" data-sub-html="Dia das Crianças na Tenda">
                                <img class="img-responsive" src="public/img/fotografias_thumbnails/chicos.jpg">
                                <div class="demo-gallery-poster">
                                    <img src="public/img/zoom.png">
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim do carousel -->

    <!-- contato -->
    <div id="contato" class="section cd-section" style="background-image: url('public/img/fotografias/cartases.jpg'); background-repeat: no-repeat; background-size: cover; box-shadow: 0 16px 24px 2px rgba(0,0,0,.14), 0 6px 30px 5px rgba(0,0,0,.12), 0 8px 10px -5px rgba(0,0,0,.2);border-radius: 0px 0px 3px 3px">
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-md-5">
                    </div>
                    <div class="col-md-5 ml-auto">
                        <div class="card card-contact" style="background-color: rgba(255,255,255,0.97); border-radius: 20px 20px 10px 10px;">
                            <!-- <form action="/enviarEmail" method="post"> -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <br />
                                        <h2 class="card-title text-center">Contate-nos<br /></h2>
                                        <span style="font-size: 14px;">Preencha o formulário abaixo ou envie um e-mail para: memorialkissconsultas@gmail.com</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group label-floating is-empty bmd-form-group">
                                            <label class="bmd-label-floating">Nome</label>
                                            <input type="text" id="nome" name="nome" class="form-control">
                                            <span class="material-input"></span>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group label-floating is-empty bmd-form-group">
                                            <label class="bmd-label-floating">Sobrenome</label>
                                            <input type="text" id="sobrenome" name="sobrenome" class="form-control">
                                            <span class="material-input"></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group label-floating is-empty bmd-form-group">
                                    <label class="bmd-label-floating">E-mail</label>
                                    <input type="email" id="email" name="email" class="form-control">
                                    <span class="material-input"></span>
                                </div>
                                <div class="form-group label-floating is-empty bmd-form-group">
                                    <label class="bmd-label-floating">Sua mensagem</label>
                                    <textarea name="mensagem" id="mensagem" class="form-control" rows="5"></textarea>
                                    <span class="material-input"></span>
                                </div>
                            </div>
                            <div class="card-footer justify-content-between">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input id="naorobo" class="form-check-input" type="checkbox" value=""> Eu não sou robô
                                        <span class="form-check-sign">
                                            <span class="check"></span>
                                        </span>
                                    </label>
                                </div>
                                <button id="btnEnviarEmail" type="submit" class="btn btn-primary pull-right">ENVIAR MENSAGEM</button>
                            </div>
                            <!-- </form> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- fim contato -->
</div>
<!-- Fim Principal -->



<!-- rodape -->
<!-- <footer class="footer footer-default">
    <div class="container">
        <div class="copyright float-right" style="font-size: 13px">
            Desenvolvedor: Rafael Nascimento<br />rdsnascimento@inf.ufpel.edu.br
        </div>
    </div>
</footer> -->
<!-- fim rodape -->