<!DOCTYPE html>
<html>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139303571-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-139303571-1');
    </script>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Memorial Kiss</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta name="description" content="O memorial é resultado de uma parceria entre a AVTSM e especialistas na área da UFSM e UFPEL.">
    <meta name="keywords" content="Memorial Kiss, Boate Kiss, Memorial Boate Kiss, Memorial Virtual Kiss,  Memorial em homenagem as vitimas da Kiss, Kiss Santa Maria, Kiss UFPEL, Kiss UFSM, UFPEL AVTSM">
    <meta name="robots" content="index, follow">
    <meta name="language" content="Portuguese">
    <meta name="generator" content="N/A">
    <meta name="author" content="Rafael Nascimento">

    <meta property="og:locale" content="pt_BR">
    <meta property="og:url" content="https://www.memorialkiss.org">
    <meta property="og:title" content="Memorial Virtual às Vítimas da Boate Kiss">
    <meta property="og:site_name" content="Memorial Virtual Kiss">
    <meta property="og:description" content="Na madrugada do dia 27 de Janeiro de 2013 mais de mil jovens estavam na casa noturna Kiss, na cidade de Santa Maria (RS).">
    <meta property="og:image" content="public/img/capa_facebook.jpg">
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="627">
    <meta property="og:type" content="website">

    <meta name="twitter:site" content="MemorialKiss" />
    <meta name="twitter:text:title" content="Memorial Kiss" />
    <meta name="twitter:image" content="public/img/capa_twitter.png" />
    <meta name="twitter:card" content="summary" />

    <!-- fontes e icones  -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Montserrat|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="public/assets/index/css/material-kit.min.css" rel="stylesheet" />
    <!-- Página -->
    <link href="public/assets/index/css/vertical-nav.css" rel="stylesheet" />
    <link href="public/assets/index/css/formatacao-principal.css" rel="stylesheet" />
    <!-- Galeria de fotos -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" rel="stylesheet"> <!-- Justificar galeria -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-galeria.css" />
    <link rel="shortcut icon" type="image/png" href="public/img/favicon.png" />
</head>

<body>
    <?= $this->content() ?>
    <!--   Core JS Files   -->
    <script src="public/assets/index/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/material-kit.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/vertical-nav.js" type="text/javascript"></script>
    <script src="public/assets/index/js/formatacao-principal.js"></script>
    <!-- Lightgallery-->
    <script src="public/assets/index/js/lightgallery/lightgallery.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-fullscreen.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-thumbnail.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-video.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-autoplay.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-zoom.min.js"></script>
    <script src="public/assets/index/js/lightgallery/transition.js"></script>
    <script src="public/assets/index/js/lightgallery/demos.js"></script>
    <script src="public/assets/index/js/lightgallery/jquery.justifiedGallery.js"></script>
</body>

</html>