<!DOCTYPE html>
<html>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139303571-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-139303571-1');
    </script>

    <meta charset="utf-8" />
    <title><?php echo $this->view->perfil_vitima['nome']; ?></title>
    <meta name="robots" content="noindex">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="content-language" content="pt-br" />

    <!-- Facebook -->
    <meta property="og:locale" content="pt_BR">
    <meta property="og:url" content="https://www.memorialkiss.org/vitima?id=<?php echo $this->view->perfil_vitima['idVitima'];?>" />
    <meta property="og:title" content="<?php echo $this->view->perfil_vitima['nome']; ?>">
    <meta property="og:description" content="Memorial Virtual em Homenagem às Vítimas da Boate Kiss">
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Memorial Virtual Kiss">
    <?php if ($this->view->perfil_vitima['idVitima'] < 10) { ?>
    <meta property="og:image" content="public/img/meta_facebook/00<?php echo $this->view->perfil_vitima['idVitima'];?>.jpg">
    <?php } else if ($this->view->perfil_vitima['idVitima'] < 100) { ?>
    <meta property="og:image" content="public/img/meta_facebook/0<?php echo $this->view->perfil_vitima['idVitima'];?>.jpg">
    <?php } else { ?>
    <meta property="og:image" content="public/img/meta_facebook/<?php echo $this->view->perfil_vitima['idVitima'];?>.jpg">
    <?php } ?>
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">

    <!-- loading -->
    <script src="public/assets/index/js/loading.js"></script>
    <!-- Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- CSS Files -->
    <link href="public/assets/index/css/material-kit.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" rel="stylesheet"> <!-- Justificar galeria -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="public/img/favicon.png">
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-galeria.css" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-vitima.css" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/loading.css" />
</head>

<body class="profile-page sidebar-collapse">
    <!-- Modais da pagina de vitimas -->
    <?= $this->content('vitimaModal') ?>

    <!-- navbar -->
    <?= $this->content('vitimaNavbar') ?>
    <div class="page-header header-filter" data-parallax="true" style="background-image: url('public/img/fotografias/frente2.jpg');"></div>
    <div class="moving-clouds" style="background-image: url(public/img/clouds.png);"></div>

    <div class="main main-raised">
        <div class="profile-content">
            <!-- Descricao, fotos e recordacoes -->
            <?= $this->content('vitimaDescricao') ?>

            <!-- Contato e enviar recordacao -->
            <?= $this->content('vitimaContato') ?>
        </div>
    </div>

    <!--   Core JS Files   -->
    <script src="public/assets/index/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/material-kit.min.js" type="text/javascript"></script>

    <!-- principal -->
    <script src="public/assets/index/js/formatacao-vitima.js"></script>
    <script src="public/assets/index/js/lightgallery/lightgallery.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-fullscreen.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-thumbnail.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-video.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-autoplay.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-zoom.js"></script>
    <script src="public/assets/index/js/lightgallery/transition.js"></script>
    <script src="public/assets/index/js/lightgallery/demos.js"></script>
    <script src="public/assets/index/js/lightgallery/jquery.justifiedGallery.js"></script>

</body>

</html>