<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        <?php echo $this->view->perfil_vitima['nome']; ?>
    </title>
    <meta name="robots" content="noindex">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="content-language" content="pt-br" />

    <!-- Facebook -->
    <meta property="og:locale" content="pt_BR">
    <meta property="og:url" content="https://www.memorialkiss.org/vitima?id=<?php echo $this->view->perfil_vitima['idVitima']; ?>" />
    <meta property="og:title" content="<?php echo $this->view->perfil_vitima['nome']; ?>">
    <meta property="og:description" content="Memorial Virtual em Homenagem às Vítimas da Boate Kiss">
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Memorial Virtual Kiss">

    <?php
    if (($this->view->perfil_vitima['idVitima'] < 151) || ($this->view->perfil_vitima['idVitima'] == 239)) {
        if ($this->view->perfil_vitima['idVitima'] < 10) {
            ?>
            <meta property="og:image" content="public/img/meta_facebook/00<?php echo $this->view->perfil_vitima['idVitima']; ?>.jpg">
        <?php
    } else if ($this->view->perfil_vitima['idVitima'] < 100){
        ?>
            <meta property="og:image" content="public/img/meta_facebook/0<?php echo $this->view->perfil_vitima['idVitima']; ?>.jpg">
        <?php
    } else {
        ?>
            <meta property="og:image" content="public/img/meta_facebook/<?php echo $this->view->perfil_vitima['idVitima']; ?>.jpg">
        <?php
    }
    ?>
    <?php
} else {
    ?>
        <meta property="og:image" content="public/img/capa_facebook.jpg">
    <?php
}
?>
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="628">

    <!-- loading -->
    <script src="public/assets/index/js/loading.js"></script>
    <!-- Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- CSS Files -->
    <link href="public/assets/index/css/material-kit.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" rel="stylesheet"> <!-- Justificar galeria -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="public/img/favicon.png">
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-galeria.css" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-vitima.css" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/loading.css" />

</head>

<body class="profile-page sidebar-collapse">
    <?= $this->content() ?>

    <!--   Core JS Files   -->
    <script src="public/assets/index/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/material-kit.min.js" type="text/javascript"></script>
    <!-- principal -->
    <script src="public/assets/index/js/formatacao-vitima.js"></script>
    <script src="public/assets/index/js/lightgallery/lightgallery.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-fullscreen.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-thumbnail.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-video.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-autoplay.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-zoom.js"></script>
    <script src="public/assets/index/js/lightgallery/transition.js"></script>
    <script src="public/assets/index/js/lightgallery/demos.js"></script>
    <script src="public/assets/index/js/lightgallery/jquery.justifiedGallery.js"></script>
    <script>
        function shareFacebook(url) {
            var w = 630;
            var h = 360;
            var left = screen.width / 2 - 630 / 2;
            var top = screen.height / 2 - 360 / 2;
            window.open('http://www.facebook.com/sharer.php?u=' + url, 'Compartilhar no facebook', 'toolbar=no, location=no, directories=no, status=no, ' + 'menubar=no, scrollbars=yes, resizable=no, copyhistory=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
        }
    </script>

<script>
        var quantidadePorPagina = 15;
        var paginaAtual = 1;
        var id = window.location.href.split('id=')[1];

        $(document).ready(function() {
            listarComentario(paginaAtual, quantidadePorPagina, id); //Chamar a função para listar os registros
        });

        function listarComentario(paginaAtual, quantidadePorPagina) {
            var dados = {
                paginaAtual: paginaAtual,
                quantidadePorPagina: quantidadePorPagina,
                id: <?php echo $this->view->perfil_vitima['idVitima']?>
            }
            $.post('/listarComentarios', dados, function(retorno) {
                var obj = JSON.parse(retorno);
                var coluna = 0;
                var textoHtml = '';
                var contRecordacoes = <?php echo $this->view->contRecordacoes;?>;
                var contDePagina = 0;

                obj.forEach(function (recordacao, index){
                    if(coluna == 0){
                        textoHtml += "<tr>\n";
                    }
                    textoHtml += `  <td>${recordacao.autor}</td>
                    <td style="text-align: right">
                        <span autor="${recordacao.autor}" dataRecordacao="${recordacao.data}" comentario="${recordacao.comentario}" onclick="modalRecordacao(this)" style="cursor: pointer">
                            <i class="fas fa-plus-circle" id="<?php if($this->view->perfil_vitima['sexo'] == '0'){echo 'iconeComentarioM';} else {echo 'iconeComentarioF';} ?>"></i>
                        </span>
                    </td>\n`;
                    coluna += 1;
                    if(coluna == 3){
                        coluna = 0;
                        textoHtml += "</tr>\n";
                    }
                });
                $("#recordacoes").html(textoHtml);

                var quantidadeDePaginas = Math.ceil(contRecordacoes/quantidadePorPagina);
                //paginacao
                if(quantidadeDePaginas > 1){
                    var maxLinksPaginas = 2;
                    var textoHtml2 = '';

                    //pagina anterior
                    if(paginaAtual == 1){
                        textoHtml2 += `<li class="page-item disabled"><span class="page-link">Anterior</span></li>\n`;
                    } else {
                        textoHtml2 += `<li class="page-item"><span class="page-link" onclick='listarComentario(${paginaAtual - 1}, ${quantidadePorPagina})'>Anterior</span></li>\n`;
                    }
                    //antes da pagina atual
                    for(let pgAnteriores = paginaAtual - maxLinksPaginas; pgAnteriores <= paginaAtual - 1; pgAnteriores++){
                        if(pgAnteriores >= 1){
                            textoHtml2 += `<li class="page-item"><span class="page-link" onclick='listarComentario(${pgAnteriores}, ${quantidadePorPagina})'>${pgAnteriores}</span></li>\n`;
                        }
                    }
                    //pagina atual
                    textoHtml2 += `<li class="page-item"><span class="page-link <?php if($this->view->perfil_vitima['sexo'] == '0'){echo 'linkPgAtivadaM';} else {echo 'linkPgAtivadaF';} ?>">${paginaAtual}</a></li>\n`;
                    //depois da pagina atual
                    for(let pgPosteriores = paginaAtual + 1; pgPosteriores <= paginaAtual + maxLinksPaginas; pgPosteriores++){
                        if(pgPosteriores <= quantidadeDePaginas){
                            textoHtml2 += `<li class="page-item"><span class="page-link" onclick='listarComentario(${pgPosteriores}, ${quantidadePorPagina})'>${pgPosteriores}</span></li>\n`;
                        }
                    }
                    //proxima pagina
                    if(paginaAtual < quantidadeDePaginas){
                        textoHtml2 += `<li class="page-item"><span class="page-link" onclick='listarComentario(${paginaAtual + 1}, ${quantidadePorPagina})'>Próximo</span></li>\n`;
                    } else {
                        textoHtml2 += `<li class="page-item disabled"><span class="page-link">Próximo</span></li>\n`;
                    }
                    $("#paginasRecordacoes").html(textoHtml2);
                }
            });
        }

        function modalRecordacao(componente){
            var autor = componente.getAttribute("autor");
            var dataHora = componente.getAttribute("dataRecordacao");
            var comentario = componente.getAttribute("comentario");

            data = dataHora.split("-");
            ano = data[0];
            mes = data[1];
            dia = data[2].split(" ")[0];
            hora = data[2].split(" ")[1].substring(0,5);
            data = "Em " + dia + "-" + mes + "-" + ano + " às " + hora; 

            $("#recordacaoTitulo").html(autor);
            $("#recordacaoData").html(data);
            $("#recordacaoTexto").html(comentario);
            $('#recordacaoModal').modal('show');
        }
    </script>
</body>

</html>