<!DOCTYPE html>
<html>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139303571-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-139303571-1');
    </script>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Memorial Kiss</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta name="description" content="Na madrugada do dia 27 de Janeiro de 2013 mais de mil jovens estavam na casa noturna Kiss, na cidade de Santa Maria (RS).">
    <meta name="keywords" content="Memorial Kiss, Boate Kiss, Memorial Boate Kiss, Memorial Virtual Kiss,  Memorial em homenagem as vitimas da Kiss, Kiss Santa Maria, Kiss UFPEL, Kiss UFSM, UFPEL AVTSM">
    <meta name="robots" content="index, follow">
    <meta name="language" content="Portuguese">
    <meta name="generator" content="N/A">
    <meta name="author" content="Rafael Nascimento">

    <meta property="og:locale" content="pt_BR">
    <meta property="og:url" content="https://www.memorialkiss.org">
    <meta property="og:title" content="Memorial Virtual às Vítimas da Boate Kiss">
    <meta property="og:site_name" content="Memorial Virtual Kiss">
    <meta property="og:description" content="Na madrugada do dia 27 de Janeiro de 2013 mais de mil jovens estavam na casa noturna Kiss, na cidade de Santa Maria (RS).">
    <meta property="og:image" content="https://www.memorialkiss.org/public/img/capa_facebook.jpg">
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="627">
    <meta property="og:type" content="website">

    <meta name="twitter:site" content="MemorialKiss" />
    <meta name="twitter:text:title" content="Memorial Kiss" />
    <meta name="twitter:image" content="https://www.memorialkiss.org/public/img/capa_facebook.jpg" />
    <meta name="twitter:card" content="summary" />

    <!-- loading -->
    <script src="public/assets/index/js/loading.js"></script>
    <!-- fontes e icones  -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Montserrat|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="public/assets/index/css/material-kit.min.css" rel="stylesheet" />
    <!-- Página -->
    <link href="public/assets/index/css/vertical-nav.css" rel="stylesheet" />
    <link href="public/assets/index/css/formatacao-principal.css" rel="stylesheet" />
    <!-- Galeria de fotos -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" rel="stylesheet"> <!-- Justificar galeria -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-galeria.css" />
    <link rel="shortcut icon" type="image/png" href="public/img/favicon.png" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/loading.css" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/carousel.css" />
</head>

<body>
    <!-- Navegacao -->
    <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="/">Inicio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <!-- menu -->
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <span class="font-navegacao">
                                <i class="material-icons">supervised_user_circle</i> Memorial
                                <div class="ripple-container"></div>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-with-icons">
                            <!-- <a href="/vidas" class="dropdown-item">
                                <i class="material-icons">people</i> 242 Vidas
                            </a> -->
                            <a href="/tragedia" class="dropdown-item">
                                <i class="material-icons">remove_circle</i> 27 de Janeiro de 2013
                            </a>
                            <a href="/futuro" class="dropdown-item">
                                <i class="material-icons">trending_up</i> Redefinindo o Futuro
                            </a>
                        </div>
                    </li>

                    <li class="nav-item navegacao">
                        <a href="/inicio#avtsm" class="nav-link">
                            <span class="font-navegacao">
                                <i class="material-icons">local_florist</i> AVTSM
                            </span>
                        </a>
                    </li>

                    <li class="nav-item navegacao">
                        <a href="/inicio#equipe" class="nav-link">
                            <span class="font-navegacao">
                                <i class="material-icons">school</i> Equipe
                            </span>
                        </a>
                    </li>

                    <li class="nav-item navegacao">
                        <a href="/inicio#galeria" class="nav-link">
                            <span class="font-navegacao">
                                <i class="material-icons">photo_library</i> Galeria
                            </span>
                        </a>
                    </li>

                    <li class="nav-item navegacao">
                        <a href="/inicio#contato" class="nav-link">
                            <span class="font-navegacao">
                                <i class="material-icons">contact_mail</i> Contato
                            </span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <!-- Fim navegacao -->

    <!-- Modal confirmação de envio de formulario -->
    <div class="modal fade" id="modalMensagem" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modalConfiguracao" style="">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modalTitulo" class="modal-title"></h5>
                </div>
                <div class="modal-body">
                    <p id="modalComentario"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Principal -->
    <main id="inicio" class="page-header header-filter cd-section" data-parallax="true" style="background-image: url('public/img/capa2.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-md-5 ml-auto" style="text-align: center;">
                    <br />
                    <h1 class="title" style="margin-top: 70px; font-family: Montserrat; font-size: 2.4em; font-weight: 300;">Memorial Virtual às Vítimas da Boate Kiss</h1>
                    <br />
                </div>
            </div>
        </div>
    </main>
    <!-- Fim Principal -->

    <?= $this->content() ?>

    <!--   Core JS Files   -->
    <script src="public/assets/index/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/material-kit.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/vertical-nav.js" type="text/javascript"></script>
    <script src="public/assets/index/js/formatacao-principal.js"></script>
    <!-- Lightgallery-->
    <script src="public/assets/index/js/lightgallery/lightgallery.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-fullscreen.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-thumbnail.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-video.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-autoplay.min.js"></script>
    <script src="public/assets/index/js/lightgallery/lg-zoom.min.js"></script>
    <script src="public/assets/index/js/lightgallery/transition.js"></script>
    <script src="public/assets/index/js/lightgallery/demos.js"></script>
    <script src="public/assets/index/js/lightgallery/jquery.justifiedGallery.js"></script>
</body>

</html>