<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Administrador</title>
    <meta name="robots" content="noindex">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta name="robots" content="noindex">
    
    <script src="public/assets/index/js/loading.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="public/assets/login/css/bootstrap.min.css" rel="stylesheet" />
    <link href="public/assets/login/css/now-ui-kit.min5438.css?v=1.2.0" rel="stylesheet" />
    <link href="public/assets/login/css/formatacao-login.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="public/img/favicon.png" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/loading.css" />
</head>

<body class="login-page sidebar-collapse">
    <?= $this->content() ?>
    
    <script src="public/assets/login/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/login/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/login/js/core/bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/login/js/now-ui-kit.min5438.js?v=1.2.0" type="text/javascript"></script>
</body>

</html>