<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard - Memorial Kiss</title>
    <meta name="robots" content="noindex">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <script src="../public/assets/index/js/loading.js"></script>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="../public/assets/dashboard/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../public/assets/dashboard/css/paper-dashboard.css?v=2.0.0" rel="stylesheet" />
    <link href="../public/assets/dashboard/css/formatacao-dashboard.css" rel="stylesheet" />
    <link href="../public/assets/infoajudar/css/uppy.min.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="../public/img/favicon.png" />
    <link rel="stylesheet" type="text/css" href="../public/assets/index/css/loading.css" />
</head>

<body>
    <div class="wrapper ">
        <!-- sidebar -->
        <div class="sidebar" data-color="white" data-active-color="danger">
            <div class="logo">
                <a href="#" class="simple-text logo-mini">
                    <div class="logo-image-small">
                        <img src="../public/assets/dashboard/img/favicon.png">
                    </div>
                </a>
                <a href="#" class="simple-text logo-normal">
                    Olá, <?php echo $_SESSION['nome'] ?>
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li id="pgvitimas">
                        <a href="/dashboard/vitimas">
                            <i class="nc-icon nc-single-02"></i>
                            <p>Vítimas</p>
                        </a>
                    </li>
                    <li id="pgrecordacoes">
                        <a href="/dashboard/recordacoes">
                            <i class="far fa-comment-alt"></i>
                            <p>Recordações <?php echo ('(' . $this->view->contComentarios['contador']) . ')'; ?></p>
                        </a>
                    </li>
                    <li id="pgfotos">
                        <a href="/dashboard/fotos">
                            <i class="fas fa-images"></i>
                            <p>Fotos
                                <?php echo ('(' . $this->view->contFotos['contador']) . ')'; ?>
                            </p>
                        </a>
                    </li>
                    <li id="pgvideos">
                        <a href="/dashboard/videos">
                            <i class="fab fa-youtube"></i>
                            <p>Vídeos
                                <?php echo ('(' . $this->view->contVideos['contador']) . ')'; ?>
                            </p>
                        </a>
                    </li>
                    <li id="pginformacoes">
                        <a href="/dashboard/informacoes">
                            <i class="far fa-address-card"></i>
                            <p>Informações
                                <?php echo ('(' . $this->view->contInfo['contador']) . ')'; ?>
                            </p>
                        </a>
                    </li>
                    <li id="pgdocumentos">
                        <a href="/dashboard/documentos">
                            <i class="far fa-folder-open"></i>
                            <p>Documentos</p>
                        </a>
                    </li>
                    <li id="pgbackup">
                        <a href="/dashboard/backup">
                            <i class="fas fa-download"></i>
                            <p>Backup em Excel</p>
                        </a>
                    </li>
                    <li class="active-pro">
                        <a href="/sair">
                            <i class="nc-icon nc-spaceship"></i>
                            <p>SAIR</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- fim sidebar -->
        <?= $this->content() ?>
        <!--   Core JS Files   -->

        <script src="../public/assets/dashboard/js/core/jquery.min.js"></script>
        <script src="../public/assets/dashboard/js/core/popper.min.js"></script>
        <script src="../public/assets/dashboard/js/core/bootstrap.min.js"></script>
        <script src="../public/assets/dashboard/js/plugins/perfect-scrollbar.jquery.min.js"></script>
        <script src="../public/assets/dashboard/js/paper-dashboard.min.js?v=2.0.0" type="text/javascript"></script>
        <script src="../public/assets/dashboard/js/ckeditor/ckeditor.js" type="text/javascript"></script>
        <script src="../public/assets/dashboard/js/formatacao-dashboard.js" type="text/javascript"></script>
        <script src="../public/assets/infoajudar/js/uppy.min.js"></script>
        <script src="../public/assets/dashboard/js/formatacao-uppy.js" type="text/javascript"></script>

        <?php
        $url = str_replace("/dashboard/", "", $_SERVER["REQUEST_URI"]); //pega qual pagina do dashboard usuario esta
        
        if ($url == 'backup') { ?>
            <script src="../public/assets/dashboard/js/alasql/jszip.js"></script>
            <script src="../public/assets/dashboard/js/alasql/xlsx.js"></script>
            <script src="../public/assets/dashboard/js/alasql/alasql.min.js"></script>
            <script src="../public/assets/dashboard/js/backupBancoDeDados.js" type="text/javascript"></script>
        <?php
        } else if ($url == 'documentos'){
        ?>
            <script src="../public/assets/dashboard/js/dashboardDocumentos.js"></script>
        <?php
        } 
        ?>
</body>

</html>