<!DOCTYPE html>
<html>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139303571-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-139303571-1');
    </script>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Conheça os Jovens</title>
    <meta name="robots" content="noindex">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <script src="public/assets/index/js/loading.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link href="public/assets/login/css/bootstrap.min.css" rel="stylesheet" />
    <link href="public/assets/index/css/material-kit.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/loading.css" />

    <!-- Galeria de fotos -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css" rel="stylesheet"> <!-- Justificar galeria -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="public/assets/index/css/formatacao-galeria.css" />
    <link rel="icon" type="image/png" href="public/img/favicon.png">

    <style>
        .main-dark {
            background: linear-gradient(135deg, rgba(10, 10, 10, 0.89) 0%, #151515 100%);
            color: #FFFFFF;
        }

        .main-raised {
            margin: 0 0 0;
            border-radius: 0px !important;
            box-shadow: none;
        }

        .fixed-top {
            position: absolute;
        }

        footer ul li div {
            color: inherit;
            padding: .9375rem;
            font-weight: 500;
            font-size: 12px;
            text-transform: uppercase;
        }
    </style>
</head>

<body class="blog-posts sidebar-collapse">
    <?= $this->content() ?>

    <script src="public/assets/index/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/popper.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="public/assets/index/js/material-kit.min.js" type="text/javascript"></script>

    <script src="public/assets/index/js/lightgallery/lightgallery.min.js"></script>
    <script src="public/assets/index/js/lightgallery/jquery.justifiedGallery.js"></script>
    <script src="public/assets/jovens/js/configLightGallery.js"></script>
    <!-- Coloca o ano no rodape -->
    <script>
        var now = new Date;
        var ano = now.getFullYear();
        $("#anoRodape").html(ano + ",");
    </script>
</body>

</html>